name: Gradle Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Inject Develocity for Gradle
      uses: bigdaz/develocity-injection-action/dv-inject-gradle@main
      with:
        develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    - name: Build with Gradle
      working-directory: gradle-example
      run: ./gradlew build
