name: Gradle Build

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Inject Develocity for Gradle
      uses: bigdaz/develocity-injection-action/dv-inject-gradle@main
    - name: Build with Gradle
      working-directory: gradle-example
      run: ./gradlew build
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
