name: Maven Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Inject Develocity for Maven
      uses: bigdaz/develocity-injection-action/dv-inject-maven@main
      with:
        project-root-directory: maven-example
        develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    - name: Build with Maven
      working-directory: maven-example
      run: ./mvnw -B verify
